<a href="https://colab.research.google.com/github/akipips/pytorch/blob/master/1basis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##pytorchとは

パイソンベースの数値計算パッケージ。numpyのndarrayに似ている。





##**Tensor**

テンソル：厳密には違うらしいですがここでは多次元配列ということにしましょう。

調べればわかりますが、これだけ理解するのも相当キツイです。
感覚的には下の資料が分かりやすいと思います。

[*テンソル*](http://solid4.mech.okayama-u.ac.jp/%E3%83%86%E3%83%B3%E3%82%BD%E3%83%AB.pdf)



In [2]:
import numpy as np 
import torch

In [6]:
#tensorを作成してみよう！
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
a=torch.rand(3,3)#3行３列　ランダム
a

tensor([[0.3931, 0.3932, 0.7740],
        [0.0074, 0.6286, 0.3264],
        [0.0249, 0.0448, 0.0884]])

In [15]:
b=torch.Tensor(3, 3)#3行3列 めちゃくちゃ小さい値をランダムに出力
b

tensor([[3.5523e-35, 0.0000e+00, 1.2612e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [4.4721e+21, 2.8799e+32, 1.3816e+31]])

In [16]:
#演算もできるよ
a+b

tensor([[3.9312e-01, 3.9324e-01, 7.7401e-01],
        [7.3797e-03, 6.2862e-01, 3.2642e-01],
        [4.4721e+21, 2.8799e+32, 1.3816e+31]])

In [17]:
#倍精度のTensor
torch.tensor([[1,2],[1,2]],dtype=torch.float64)

tensor([[1., 2.],
        [1., 2.]], dtype=torch.float64)

In [18]:
#numpyへの変換も簡単！
a.numpy()

array([[0.3931206 , 0.39324474, 0.77400726],
       [0.00737971, 0.6286232 , 0.3264165 ],
       [0.02492803, 0.04482484, 0.08840799]], dtype=float32)

####インデクシング
添え字を使った配列への操作全般のこと


In [3]:
#インデクシング:ndarrayとほぼ同じ
t=torch.tensor([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
t

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

In [4]:
t[1:3]

tensor([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [5]:
t[0]

tensor([1, 2, 3, 4, 5])

In [6]:
t[0,3]

tensor(4)

In [4]:
t[1:3,:]

tensor([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [6]:
t[:,1:3]

tensor([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]])

In [7]:
t[1:3,1:3]

tensor([[ 7,  8],
        [12, 13]])

In [12]:
t[t%2==0]=0#条件式を[]に入れることでこんなこともできる。ブール型が要素になっている配列をマスク配列という。
t

tensor([[ 1,  0,  3,  0,  5],
        [ 0,  7,  0,  9,  0],
        [11,  0, 13,  0, 15],
        [ 0, 17,  0, 19,  0],
        [21,  0, 23,  0, 25]])

In [13]:
t[-1]

tensor([21,  0, 23,  0, 25])

IndexError: ignored

In [17]:
t[::-1,::-1]

ValueError: ignored