<a href="https://colab.research.google.com/github/akipips/pytorch/blob/master/2_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np 
import torch

##pytorchの演算について

Tensor同士かTensorとpythonのスカラーの組み合わせのみサポートされている。
また、float型とdouble型の演算などもエラーとなる。
numpyと同様にブロードキャストが適用されることもある。


In [23]:
t=torch.tensor([1,1,1])
t

tensor([1, 1, 1])

In [24]:
#ブロードキャストの例
t*(-1)

tensor([-1, -1, -1])

In [25]:
t*t

tensor([1, 1, 1])

In [30]:
a=torch.zeros(1,3)#tensor([[0., 0., 0.]])

t*a

tensor([[0., 0., 0.]])

In [32]:
b=torch.tensor([[1],
                [2],
                [3]])

t*b

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

##組み込み関数

ndarrayとあんまり変わらない。abs,exp,sqrtなど


In [35]:
t=torch.tensor([-1,2,3])
torch.abs(t)#絶対値

tensor([1, 2, 3])

In [41]:
torch.exp(torch.tensor([1,2.]))

tensor([2.7183, 7.3891])

In [42]:
torch.sqrt(torch.tensor([1,2.]))#何故2に.をつけるかは一度外してみて実行してみればわかります。

tensor([1.0000, 1.4142])

In [43]:
torch.mean(t)#floatじゃなきゃけいさんできねーよって怒られちゃいました

RuntimeError: ignored

In [47]:
torch.mean(torch.tensor([2020,6,24.]))#この.でfloat型になるってことですね！

tensor(683.3333)

In [55]:
a=torch.tensor([[1,1,1],
                [2,2,2.]])

b=torch.tensor([[1],
                [2.]])

a.view(1,6)#ndarrayにおけるreshapeに相当

tensor([[1., 1., 1., 2., 2., 2.]])

In [56]:
a.t()#転置

tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])

In [57]:
torch.cat([a,b],dim=1)#合成

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.]])

##線形代数

ここからはベクトルの内積などを扱う。


In [67]:
#matmal

a=torch.tensor([[1,2,3.],
                [4,5,6.]])

b=torch.tensor([[1,2],
                [3,4],
                [5,6.]])

torch.mm(a,b)

#dotやmvなどもあるけど次の演算が自動化されていて便利

tensor([[22., 28.],
        [49., 64.]])

In [68]:
c=torch.tensor([1,2,3.])

In [70]:
torch.matmul(c,b)#matmul:引数の種類で自動的にmm,mv,dotを決めてくれる

tensor([22., 28.])

In [71]:
torch.matmul(c,c)

tensor(14.)